--MYSQL IF ELSE 
--PROGRAMLAMA DILINDE KULLANAN SART ISLEMLERI
--MYSQL KULLANIMI ISE


--IF KULLANIMI

IF(SART,"DOGRU","YANLIS");

--TEK BASINA KULLAMI

SELECT IF(5>4,"BES BUYUKTUR","4 BUYUKTUR");

OUTPUT = #BES BUYUKTUR



TABLONUZDAN ORNEKLER YAPABILIRSINIZ


SELECT IF(DOGUM_TARIH >2002-01-01, "RESIT","RESIT DEGIL") FROM PERSONEL;

ORNEKLERI COGALTABILIRSINIZ



--IF,ELSE--ELSEIF KULLANIMI

PROCEDURE-TRIGER-VE DIGER FONKSÝYONLARDA KULLANIMI DAHA YAYGINDIR

DELÝMÝTTER //
CREATE PROCEDURE GIR(IN SAYI INT(11),OUT DEGER VARCHAR(20))
--OUT DEGER TUTAR
BEGÝN

IF SAYI = 1 THEN
	SET DEGER = 'IBRAHIM';

ELSEÝF SAYI = 2 THEN
	SET DEGER = 'SELIN';

ELSE SAYI = 2 THEN
	SET DEGER = 'DILARA';

ELSE 
	SET DEGER = '1 2 3 ARASINDA DEGER GIR :)'

END ÝF;
END//
DELÝMÝTTER ;

-- KULLANIMI BOYLE PROCEDURE DEGER VERELIM
-- DEGISKEN ACIP PROCEDURE GIRDIGIMIZ DEGERI DEGISKENE ATAYALIM
-- SONRA SELECT ILE DEGISKENI YAZDIRALIM

SET @ABC = 0;
CALL GIR(1,@ABC);
SELECT @ABC
OUT = 'IBRAHIM' 


ORNEKLERI COGALTABILIR
MYSQL DOCUMENT INCELEYEBILIRSINIZ
https://dev.mysql.com/doc/refman/8.0/en/if.html












